title: John Smith
description: My Personal Blog
author: John Smith
logo: /static/img/avatar.png
github: https://github.com/gismo-ci
about: Freelance developer

baseurl: "https://gismo-ci.github.io"
url: "https://gismo-ci.github.io"

allowsearch: false

disqus_shortname: aboutashu
google_analytics: UA-00000000-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
